### ISSUE TITLE
figure out how to reject multiple `infra` type constructs at schema level when they are provided in their explicit form.

### ISSUE THREAD

**Issue by 3p3r** [stelligent/mutato#21]
Per MVP design docs, `infra` constructs (`network`, `cluster`, and `cicd`) can be either omitted from `mu.yml` or appear at most once. When provided in the shorthand version, this issue is automatically resolved due to the nature of json objects (two keys with the same name cannot coexist in the same object).

When provided in the explicit version, the following `mu.yml` should be rejected at the schema level:

```
mu:
  name1:
    type: cicd
    ...

  name2:
    type: cicd
    ...
```
