### ISSUE TITLE
implement mvp construct: database

### ISSUE THREAD

**Issue by 3p3r** [stelligent/mutato#24]
MVP construct schema:
```
database:
  provider: rds, aurora, serverless-aurora, dynamodb, docdb
  engine: mysql, postgresql, etc.
  ...
```
