### ISSUE TITLE
implement mvp construct: storage

### ISSUE THREAD

**Issue by 3p3r** [stelligent/mutato#25]
MVP construct schema:
```
storage:
  provider: s3, efs
  mount: /dev/whatever
  ...
```
